#!/bin/bash

clear
echo " _   ___        __    _          _"
echo "| | | \ \      / /   | |__   ___| |_ __   ___ _ __"
echo "| |_| |\ \ /\ / /____| '_ \ / _ \ | '_ \ / _ \ '__|"
echo "|  _  | \ V  V /_____| | | |  __/ | |_) |  __/ |"
echo "|_| |_|  \_/\_/      |_| |_|\___|_| .__/ \___|_|"
echo "                                  |_|"
echo -e "\n形式は以下の通りです\n"
echo  "  1. dmesg"
echo  "  2. lspci"
echo  "  3. lsusb"
echo

echo -n "番号を数字で入力して下さい: "
read -r chk_type

clear
if [[ $chk_type == 1 ]] || [[ "$chk_type" == "１" ]]; then
  echo -e "\"journalctl -k --no-pager\" を実行します\n"
  journalctl -k --no-pager
elif [[ $chk_type == 2 ]] || [[ "$chk_type" == "２" ]]; then
  echo -e "\"lspci\" を実行します\n"
  lspci
elif [[ $chk_type == 3 ]] || [[ "$chk_type" == "３" ]]; then
  echo -e "\"lsusb\" を実行します\n"
  lsusb
else
  echo -n
fi
echo
exit 0
