#!/bin/bash

clear
if [ ! $(command -v whiptail) ]; then
  if [ $(id -u) != 0 ]; then SUDO="sudo "; fi
  echo -e "\n\n必須ソフトウェアが削除されているため､\n\"help-hw\" の実行に失敗しました｡\n\n"
  echo -e "解決するには？\n"
  echo -e "${SUDO}apt install -y whiptail\n\n上記のコマンドをインターネットに接続されている環境で実行します\n"
  exit 1
fi
Help_RUN=$(whiptail --title "HW-Helper" --menu "\n選択してください" 0 0 0 --ok-button "選択" --cancel-button "終了" --notags 'journalctl -k --no-pager' "dmesg" 'lspci' "lspci" 'lsusb' "lsusb" 3>&1 1>&2 2>&3)
if [ $? != 0 ]; then exit 1; fi
declare -A Help_MSG=(["journalctl -k --no-pager"]="dmesg" ["lspci"]="lspci" ["lsusb"]="lsusb")
Help_OUT=$(whiptail --title "HW-Helper" --yesno "\nファイルに出力しますか？" 0 0 --yes-button "する" --no-button "しない" --defaultno 3>&1 1>&2 2>&3)
if [ $? == 0 ]; then
  Help_LOG="Help-HW_${Help_MSG[$Help_RUN]}_$(date +%F-%H-%M-%S).log"
  $Help_RUN|tee -a $Help_LOG 2>/dev/null
  if [ $? == 0 ]; then
    echo -e "\n\nCPU Info\n\n$(lscpu)">>$Help_LOG
    echo -e "\n\nRAM Info\n$(free -h)">>$Help_LOG
    echo -e "\n\nStorage Info\n\n$(df -h)">>$Help_LOG
    echo -e "\nログは \"$Help_LOG\" としてファイルに保存されました｡\n"
    exit 0
  else
    echo -e "\n書込権限不足等の理由でファイルを書き込めませんでした｡\n"
    exit 1
  fi
else
  $Help_RUN
  echo
  exit 0
fi
